com.webos.service.camera doesn't respect libdir variable
:Release Notes:
Fix build issue for aarch64 and x86_64

:Detailed Notes
Fix below QA issue for aarch64 and x86_64 build:
ERROR: QA Issue: com.webos.service.camera: Files/directories
were installed but not shipped in any package:
  /usr/lib/libv4l2-camera-plugin.so
  /usr/lib/libcamera_hal.so.1
  /usr/lib/libv4l2-camera-plugin.so.1
  /usr/lib/libv4l2-camera-plugin.so.1.0
  /usr/lib/libcamera_hal.so
  /usr/lib/libcamera_hal.so.1.0

:Testing Performed:
Build succesfully.
No test cases required as only QA issue.

:QA Notes:
NA

:Issues Addressed:
[PLAT-81016] Fix com.webos.service.camera build issue for aarch64 and
x86_64

Change-Id: I7d40588fc3058be872c13e21656cd6c3565523a2