Fix build with gcc-13
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/538296

FAILED: src/services/hal/CMakeFiles/com.webos.service.camera2.hal.dir/device_controller.cpp.o
TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/recipe-sysroot-native/usr/bin/arm-starfishmllib32-linux-gnueabi/arm-starfishmllib32-linux-gnueabi-g++  -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/include/public -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/include/public/camera -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/include/public/camera/addon -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/include/public/camera/hal -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/include/public/camera/notifier -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/include/public/camera/solution -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/include/private -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal/hal_if -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/common/ipc -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/common/shm -mthumb -mfpu=neon -mfloat-abi=softfp -mcpu=cortex-a9 -mtune=cortex-a9 -funwind-tables -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64  --sysroot=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git=/usr/src/debug/lib32-com.webos.service.camera/1.0.0-43-r5  -fdebug-prefix-map=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git=/usr/src/debug/lib32-com.webos.service.camera/1.0.0-43-r5  -fmacro-prefix-map=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/build=/usr/src/debug/lib32-com.webos.service.camera/1.0.0-43-r5  -fdebug-prefix-map=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/build=/usr/src/debug/lib32-com.webos.service.camera/1.0.0-43-r5  -fdebug-prefix-map=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/recipe-sysroot-native=  -fvisibility-inlines-hidden  -Wall -funwind-tables -Wall -rdynamic -lrt -Werror -Wno-psabi -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/lib32-recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -g -std=gnu++17 -MD -MT src/services/hal/CMakeFiles/com.webos.service.camera2.hal.dir/device_controller.cpp.o -MF src/services/hal/CMakeFiles/com.webos.service.camera2.hal.dir/device_controller.cpp.o.d -o src/services/hal/CMakeFiles/com.webos.service.camera2.hal.dir/device_controller.cpp.o -c TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal/device_controller.cpp
TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal/device_controller.cpp: In member function 'DEVICE_RETURN_CODE_T DeviceControl::stopPreview(void*, int)':
TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal/device_controller.cpp:681:40: error: expected unqualified-id before '&' token
  681 |         catch (const std::system_error &e)
      |                                        ^
TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal/device_controller.cpp:681:39: error: expected ')' before '&' token
  681 |         catch (const std::system_error &e)
      |               ~                       ^~
      |                                       )
TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal/device_controller.cpp:681:40: error: expected '{' before '&' token
  681 |         catch (const std::system_error &e)
      |                                        ^
TOPDIR/BUILD/work/o22-starfishmllib32-linux-gnueabi/lib32-com.webos.service.camera/1.0.0-43-r5/git/src/services/hal/device_controller.cpp:681:41: error: 'e' was not declared in this scope
  681 |         catch (const std::system_error &e)
      |                                         ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Change-Id: Ie280c23fd2d8c294ace7800198e6d4a391851fda
(cherry picked from commit b0409d44bbe7fec24787bda27188940cd3bbcb27)