Fix build with gcc-13
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/699390

FAILED: CMakeFiles/com.webos.service.camera2.dir/src/service/device_controller.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot  -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/files -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/files/sysbus -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/files/systemd -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/service -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/service/notifier -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/service/notifier/pdm -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/service/solutions -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/include/aif -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/hal -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/hal/v4l2 -I/usr/src/gtest/include -mcpu=cortex-a72 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git=/usr/src/debug/com.webos.service.camera/1.0.0-37-r11  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git=/usr/src/debug/com.webos.service.camera/1.0.0-37-r11  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/build=/usr/src/debug/com.webos.service.camera/1.0.0-37-r11  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/build=/usr/src/debug/com.webos.service.camera/1.0.0-37-r11  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot-native=  -fvisibility-inlines-hidden -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/lib/glib-2.0/include -Wall -funwind-tables -Wall -rdynamic -std=c++14 -g -lrt -Werror=return-type -Wno-stringop-truncation -Wno-stringop-overflow -DFEATURE_LG_AUTOCONTRAST -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/include/aif -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/recipe-sysroot/usr/include/opencv4 -DFEATURE_LG_AIF_FACEDETECTION -DFEATURE_LG_DUMMY -g -MD -MT CMakeFiles/com.webos.service.camera2.dir/src/service/device_controller.cpp.o -MF CMakeFiles/com.webos.service.camera2.dir/src/service/device_controller.cpp.o.d -o CMakeFiles/com.webos.service.camera2.dir/src/service/device_controller.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/service/device_controller.cpp
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/service/device_controller.cpp: In member function 'DEVICE_RETURN_CODE_T DeviceControl::stopPreview(void*, int)':
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-37/git/src/service/device_controller.cpp:671:40: error: expected unqualified-id before '&' token
  671 |         catch (const std::system_error &e)
      |                                        ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-27901] CCC: Various build fixes

Change-Id: I4545ffeec79b4bc8e195bfa7d5ce9aa4f766afdd